[changelog]
header = ""
body = """
{%- for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{%- for commit in commits %}
- {{ commit.message | split(pat="\n") | first | trim }}\
  {%- if commit.scope %} *({{ commit.scope }})* {% endif %}\
  ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/commit/{{ commit.id }}))
{%- endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactor" },
  { message = "^style", group = "Styling" },
  { message = "^doc|^docs", group = "Documentation" },
  { message = "^ci", group = "CI" },
  { message = "^chore", skip = true },
]
tag_pattern = "v[0-9].*"

[remote.github]
owner = "CyrusZhou-CN"
repo = "TorrentDeck"
